#!/bin/bash

program=$(basename $0)

# default settings
eth=eth0              # interface to monitor
port=32400            # Plex port to monitor
state=/dev/shm/plex_track.state   # per-IP last-seen state file read by s3_sleep
throttle=300          # minimum seconds between syslog messages per IP

# program control
quit_flag=no          # signal program exit

# options to overwrite defaults
while getopts "e:X:q" opt; do
  case $opt in
    e) eth=$OPTARG ;;
    X) port=$OPTARG ;;
    q) quit_flag=yes ;;
  esac
done

lockfile=/var/lock/plex_track.lck
if [[ -f $lockfile ]]; then
  # The file exists so read the PIDs to see if they are still running
  lock_content=$(head -n 1 $lockfile)

  # Parse the lockfile content (format: monitor_pid:tcpdump_pid or just monitor_pid for old format)
  if [[ $lock_content =~ ^([0-9]+):([0-9]+)$ ]]; then
    monitor_pid=${BASH_REMATCH[1]}
    tcpdump_pid=${BASH_REMATCH[2]}
  else
    # Old format - just monitor PID
    monitor_pid=$lock_content
    tcpdump_pid=""
  fi

  if [[ -z $(ps -p $monitor_pid|grep $monitor_pid) ]]; then
    if [[ $quit_flag == no ]]; then
      # The process is not running, echo current PID into lock file
      echo $$ >$lockfile
    else
      echo "$program $monitor_pid is not currently running "
      rm -f $lockfile
      exit 0
    fi
  else
    if [[ $quit_flag == yes ]]; then
      echo killing $program process $monitor_pid
      echo killing $program process $monitor_pid | logger -t$program
      kill $monitor_pid

      # Also kill tcpdump process if we have its PID
      if [[ -n $tcpdump_pid && -n $(ps -p $tcpdump_pid 2>/dev/null|grep $tcpdump_pid) ]]; then
        echo killing tcpdump process $tcpdump_pid
        echo killing tcpdump process $tcpdump_pid | logger -t$program
        kill $tcpdump_pid
      fi

      rm -f $lockfile
      exit 0
    else
      echo "$program is already running [$monitor_pid]"
      exit 1
    fi
  fi
else
  if [[ $quit_flag == yes ]]; then
    echo "$program not currently running "

    # Kill any orphaned tcpdump processes that might be running for this script
    orphaned_pids=$(pgrep -f "tcpdump.*dst port $port")
    if [[ -n $orphaned_pids ]]; then
      echo "Found orphaned tcpdump processes: $orphaned_pids"
      echo "Killing orphaned tcpdump processes: $orphaned_pids" | logger -t$program
      kill $orphaned_pids 2>/dev/null
    fi

    exit 0
  else
    echo $$ >$lockfile
  fi
fi

# Capture inbound connection attempts (SYN without ACK) to the Plex port.
# -tt prints epoch timestamps, so no gawk systime() dependency is needed.
tcpdump -lnn -tt -i $eth "tcp[tcpflags] & (tcp-syn|tcp-ack) == tcp-syn and dst port $port" 2>/dev/null | \
awk -v interface=$eth -v program="$program" -v state="$state" -v throttle=$throttle '{
    # Expected line: <epoch> IP <src.ip.and.port> > <dst.ip.and.port>: Flags [S], ...
    if ($2 != "IP") next
    ts = int($1)
    n = split($3, a, ".")
    if (n < 5) next
    ip = a[1] "." a[2] "." a[3] "." a[4]
    last[ip] = ts
    # Rewrite state file with last-seen timestamp per IP
    tmp = state ".tmp"
    for (i in last) print last[i], i > tmp
    close(tmp)
    system("mv " tmp " " state)
    # Throttled syslog message per IP
    if (ts - logged[ip] >= throttle) {
        logged[ip] = ts
        message = "Plex connection attempt from IP: " ip " on " interface
        system("logger -t \"" program "\" \"" message "\"")
    }
}' &

# Capture the PID of the tcpdump process
tcpdump_pid=$!

while [[ -f $lockfile ]]; do
  sleep 600
done &

# Store both PIDs in the lockfile (monitor_pid:tcpdump_pid)
monitor_pid=$!
echo "$monitor_pid:$tcpdump_pid" >$lockfile
echo "$program process ID $monitor_pid started (tcpdump PID: $tcpdump_pid), To terminate it, type: $program -q"
echo "$program process ID $monitor_pid started (tcpdump PID: $tcpdump_pid), To terminate it, type: $program -q"|logger -t$program
disown %%
